[tool.poetry]
name = "speakerz"
version = "0.0.1"
description = "Beets, but for the server!"
authors = ["Sakooooo"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
